[build]
  command = "ng build --configuration production"
  publish = "dist/atualizacaoMonetaria/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
